@startuml user-service-use-case
left to right direction

actor Admin
actor User

User <|- Admin

package user-service {
    usecase "Register" as register
    usecase "Login" as login
    usecase "Verify Email" as verifyEmail
    usecase "Forgot Password" as forgotPassword
    usecase "Refresh Token" as refreshToken
    usecase "View Profile" as viewProfile
    usecase "Update Profile" as updateProfile
    usecase "Logout" as logout
}

User -> register
User --> login
User --> verifyEmail
User --> forgotPassword
User --> refreshToken
User ---> viewProfile
User ---> updateProfile
User ----> logout
