services:
    opa:
        image: openpolicyagent/opa:1.1.0-static
        command:
            [
                "run",
                "--server",
                # "--log-level",
                # "debug",
                "--addr",
                ":8181",
                "/bundle.tar.gz",
            ]
        ports:
            - "8181:8181"
        networks:
            - core-net
        volumes:
            - ../../.dist/bundle.tar.gz:/bundle.tar.gz:ro
