// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.31.0
// 	protoc        v5.29.0
// source: notification/sms.proto

package notification_proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Sms struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Recipient string `protobuf:"bytes,1,opt,name=recipient,proto3" json:"recipient,omitempty"`
	Body      string `protobuf:"bytes,2,opt,name=body,proto3" json:"body,omitempty"`
}

func (x *Sms) Reset() {
	*x = Sms{}
	if protoimpl.UnsafeEnabled {
		mi := &file_notification_sms_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Sms) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Sms) ProtoMessage() {}

func (x *Sms) ProtoReflect() protoreflect.Message {
	mi := &file_notification_sms_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Sms.ProtoReflect.Descriptor instead.
func (*Sms) Descriptor() ([]byte, []int) {
	return file_notification_sms_proto_rawDescGZIP(), []int{0}
}

func (x *Sms) GetRecipient() string {
	if x != nil {
		return x.Recipient
	}
	return ""
}

func (x *Sms) GetBody() string {
	if x != nil {
		return x.Body
	}
	return ""
}

type BulkSms struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Recipients []string `protobuf:"bytes,1,rep,name=recipients,proto3" json:"recipients,omitempty"`
	Body       string   `protobuf:"bytes,2,opt,name=body,proto3" json:"body,omitempty"`
}

func (x *BulkSms) Reset() {
	*x = BulkSms{}
	if protoimpl.UnsafeEnabled {
		mi := &file_notification_sms_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BulkSms) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BulkSms) ProtoMessage() {}

func (x *BulkSms) ProtoReflect() protoreflect.Message {
	mi := &file_notification_sms_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BulkSms.ProtoReflect.Descriptor instead.
func (*BulkSms) Descriptor() ([]byte, []int) {
	return file_notification_sms_proto_rawDescGZIP(), []int{1}
}

func (x *BulkSms) GetRecipients() []string {
	if x != nil {
		return x.Recipients
	}
	return nil
}

func (x *BulkSms) GetBody() string {
	if x != nil {
		return x.Body
	}
	return ""
}

var File_notification_sms_proto protoreflect.FileDescriptor

var file_notification_sms_proto_rawDesc = []byte{
	0x0a, 0x16, 0x6e, 0x6f, 0x74, 0x69, 0x66, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x2f, 0x73,
	0x6d, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x2f, 0x68, 0x61, 0x72, 0x6d, 0x6f, 0x6e,
	0x69, 0x66, 0x79, 0x2e, 0x6d, 0x6f, 0x76, 0x69, 0x65, 0x5f, 0x72, 0x65, 0x73, 0x65, 0x72, 0x76,
	0x61, 0x74, 0x69, 0x6f, 0x6e, 0x5f, 0x73, 0x79, 0x73, 0x74, 0x65, 0x6d, 0x2e, 0x6e, 0x6f, 0x74,
	0x69, 0x66, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x22, 0x37, 0x0a, 0x03, 0x53, 0x6d, 0x73,
	0x12, 0x1c, 0x0a, 0x09, 0x72, 0x65, 0x63, 0x69, 0x70, 0x69, 0x65, 0x6e, 0x74, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x09, 0x72, 0x65, 0x63, 0x69, 0x70, 0x69, 0x65, 0x6e, 0x74, 0x12, 0x12,
	0x0a, 0x04, 0x62, 0x6f, 0x64, 0x79, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x62, 0x6f,
	0x64, 0x79, 0x22, 0x3d, 0x0a, 0x07, 0x42, 0x75, 0x6c, 0x6b, 0x53, 0x6d, 0x73, 0x12, 0x1e, 0x0a,
	0x0a, 0x72, 0x65, 0x63, 0x69, 0x70, 0x69, 0x65, 0x6e, 0x74, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28,
	0x09, 0x52, 0x0a, 0x72, 0x65, 0x63, 0x69, 0x70, 0x69, 0x65, 0x6e, 0x74, 0x73, 0x12, 0x12, 0x0a,
	0x04, 0x62, 0x6f, 0x64, 0x79, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x62, 0x6f, 0x64,
	0x79, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_notification_sms_proto_rawDescOnce sync.Once
	file_notification_sms_proto_rawDescData = file_notification_sms_proto_rawDesc
)

func file_notification_sms_proto_rawDescGZIP() []byte {
	file_notification_sms_proto_rawDescOnce.Do(func() {
		file_notification_sms_proto_rawDescData = protoimpl.X.CompressGZIP(file_notification_sms_proto_rawDescData)
	})
	return file_notification_sms_proto_rawDescData
}

var file_notification_sms_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_notification_sms_proto_goTypes = []interface{}{
	(*Sms)(nil),     // 0: harmonify.movie_reservation_system.notification.Sms
	(*BulkSms)(nil), // 1: harmonify.movie_reservation_system.notification.BulkSms
}
var file_notification_sms_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_notification_sms_proto_init() }
func file_notification_sms_proto_init() {
	if File_notification_sms_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_notification_sms_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Sms); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_notification_sms_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BulkSms); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_notification_sms_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_notification_sms_proto_goTypes,
		DependencyIndexes: file_notification_sms_proto_depIdxs,
		MessageInfos:      file_notification_sms_proto_msgTypes,
	}.Build()
	File_notification_sms_proto = out.File
	file_notification_sms_proto_rawDesc = nil
	file_notification_sms_proto_goTypes = nil
	file_notification_sms_proto_depIdxs = nil
}
