// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.2
// 	protoc        v5.29.3
// source: notification/sms.proto

package notification_proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SendSmsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Recipient     string                 `protobuf:"bytes,1,opt,name=recipient,proto3" json:"recipient,omitempty"`
	Body          string                 `protobuf:"bytes,2,opt,name=body,proto3" json:"body,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendSmsRequest) Reset() {
	*x = SendSmsRequest{}
	mi := &file_notification_sms_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendSmsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendSmsRequest) ProtoMessage() {}

func (x *SendSmsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_notification_sms_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendSmsRequest.ProtoReflect.Descriptor instead.
func (*SendSmsRequest) Descriptor() ([]byte, []int) {
	return file_notification_sms_proto_rawDescGZIP(), []int{0}
}

func (x *SendSmsRequest) GetRecipient() string {
	if x != nil {
		return x.Recipient
	}
	return ""
}

func (x *SendSmsRequest) GetBody() string {
	if x != nil {
		return x.Body
	}
	return ""
}

type SendSmsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SmsId         string                 `protobuf:"bytes,1,opt,name=smsId,proto3" json:"smsId,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendSmsResponse) Reset() {
	*x = SendSmsResponse{}
	mi := &file_notification_sms_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendSmsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendSmsResponse) ProtoMessage() {}

func (x *SendSmsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_notification_sms_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendSmsResponse.ProtoReflect.Descriptor instead.
func (*SendSmsResponse) Descriptor() ([]byte, []int) {
	return file_notification_sms_proto_rawDescGZIP(), []int{1}
}

func (x *SendSmsResponse) GetSmsId() string {
	if x != nil {
		return x.SmsId
	}
	return ""
}

type BulkSendSmsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Recipients    []string               `protobuf:"bytes,1,rep,name=recipients,proto3" json:"recipients,omitempty"`
	Body          string                 `protobuf:"bytes,2,opt,name=body,proto3" json:"body,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BulkSendSmsRequest) Reset() {
	*x = BulkSendSmsRequest{}
	mi := &file_notification_sms_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BulkSendSmsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BulkSendSmsRequest) ProtoMessage() {}

func (x *BulkSendSmsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_notification_sms_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BulkSendSmsRequest.ProtoReflect.Descriptor instead.
func (*BulkSendSmsRequest) Descriptor() ([]byte, []int) {
	return file_notification_sms_proto_rawDescGZIP(), []int{2}
}

func (x *BulkSendSmsRequest) GetRecipients() []string {
	if x != nil {
		return x.Recipients
	}
	return nil
}

func (x *BulkSendSmsRequest) GetBody() string {
	if x != nil {
		return x.Body
	}
	return ""
}

type BulkSendSmsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SmsIds        []string               `protobuf:"bytes,1,rep,name=smsIds,proto3" json:"smsIds,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BulkSendSmsResponse) Reset() {
	*x = BulkSendSmsResponse{}
	mi := &file_notification_sms_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BulkSendSmsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BulkSendSmsResponse) ProtoMessage() {}

func (x *BulkSendSmsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_notification_sms_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BulkSendSmsResponse.ProtoReflect.Descriptor instead.
func (*BulkSendSmsResponse) Descriptor() ([]byte, []int) {
	return file_notification_sms_proto_rawDescGZIP(), []int{3}
}

func (x *BulkSendSmsResponse) GetSmsIds() []string {
	if x != nil {
		return x.SmsIds
	}
	return nil
}

var File_notification_sms_proto protoreflect.FileDescriptor

var file_notification_sms_proto_rawDesc = []byte{
	0x0a, 0x16, 0x6e, 0x6f, 0x74, 0x69, 0x66, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x2f, 0x73,
	0x6d, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x2f, 0x68, 0x61, 0x72, 0x6d, 0x6f, 0x6e,
	0x69, 0x66, 0x79, 0x2e, 0x6d, 0x6f, 0x76, 0x69, 0x65, 0x5f, 0x72, 0x65, 0x73, 0x65, 0x72, 0x76,
	0x61, 0x74, 0x69, 0x6f, 0x6e, 0x5f, 0x73, 0x79, 0x73, 0x74, 0x65, 0x6d, 0x2e, 0x6e, 0x6f, 0x74,
	0x69, 0x66, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x22, 0x42, 0x0a, 0x0e, 0x53, 0x65, 0x6e,
	0x64, 0x53, 0x6d, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1c, 0x0a, 0x09, 0x72,
	0x65, 0x63, 0x69, 0x70, 0x69, 0x65, 0x6e, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09,
	0x72, 0x65, 0x63, 0x69, 0x70, 0x69, 0x65, 0x6e, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x62, 0x6f, 0x64,
	0x79, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x62, 0x6f, 0x64, 0x79, 0x22, 0x27, 0x0a,
	0x0f, 0x53, 0x65, 0x6e, 0x64, 0x53, 0x6d, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x12, 0x14, 0x0a, 0x05, 0x73, 0x6d, 0x73, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x05, 0x73, 0x6d, 0x73, 0x49, 0x64, 0x22, 0x48, 0x0a, 0x12, 0x42, 0x75, 0x6c, 0x6b, 0x53, 0x65,
	0x6e, 0x64, 0x53, 0x6d, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1e, 0x0a, 0x0a,
	0x72, 0x65, 0x63, 0x69, 0x70, 0x69, 0x65, 0x6e, 0x74, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x09,
	0x52, 0x0a, 0x72, 0x65, 0x63, 0x69, 0x70, 0x69, 0x65, 0x6e, 0x74, 0x73, 0x12, 0x12, 0x0a, 0x04,
	0x62, 0x6f, 0x64, 0x79, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x62, 0x6f, 0x64, 0x79,
	0x22, 0x2d, 0x0a, 0x13, 0x42, 0x75, 0x6c, 0x6b, 0x53, 0x65, 0x6e, 0x64, 0x53, 0x6d, 0x73, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x6d, 0x73, 0x49, 0x64,
	0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x09, 0x52, 0x06, 0x73, 0x6d, 0x73, 0x49, 0x64, 0x73, 0x62,
	0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_notification_sms_proto_rawDescOnce sync.Once
	file_notification_sms_proto_rawDescData = file_notification_sms_proto_rawDesc
)

func file_notification_sms_proto_rawDescGZIP() []byte {
	file_notification_sms_proto_rawDescOnce.Do(func() {
		file_notification_sms_proto_rawDescData = protoimpl.X.CompressGZIP(file_notification_sms_proto_rawDescData)
	})
	return file_notification_sms_proto_rawDescData
}

var file_notification_sms_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_notification_sms_proto_goTypes = []any{
	(*SendSmsRequest)(nil),      // 0: harmonify.movie_reservation_system.notification.SendSmsRequest
	(*SendSmsResponse)(nil),     // 1: harmonify.movie_reservation_system.notification.SendSmsResponse
	(*BulkSendSmsRequest)(nil),  // 2: harmonify.movie_reservation_system.notification.BulkSendSmsRequest
	(*BulkSendSmsResponse)(nil), // 3: harmonify.movie_reservation_system.notification.BulkSendSmsResponse
}
var file_notification_sms_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_notification_sms_proto_init() }
func file_notification_sms_proto_init() {
	if File_notification_sms_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_notification_sms_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_notification_sms_proto_goTypes,
		DependencyIndexes: file_notification_sms_proto_depIdxs,
		MessageInfos:      file_notification_sms_proto_msgTypes,
	}.Build()
	File_notification_sms_proto = out.File
	file_notification_sms_proto_rawDesc = nil
	file_notification_sms_proto_goTypes = nil
	file_notification_sms_proto_depIdxs = nil
}
