global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: "prometheus"
    scrape_interval: 5s
    static_configs:
      - targets: ["localhost:9090"]

  - job_name: "postgres"
    static_configs:
      - targets: ["localhost:9187"] # PostgreSQL Exporter

  - job_name: "redis"
    static_configs:
      - targets: ["localhost:9121"] # Redis Exporter

  - job_name: "kafka"
    static_configs:
      - targets: ["localhost:9308"] # Kafka Exporter
