services:
    elasticsearch:
        image: elasticsearch:8.17.0
        ports:
            - "9200:9200"
        environment:
            - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
            - bootstrap.memory_lock=true
            - discovery.type=single-node
            - node.name=elasticsearch
        volumes:
            - ../../../.data/elasticsearch:/usr/share/elasticsearch/data

    mongodb:
        # If you are using a Raspberry Pi, use mongo:4.4.18
        image: mongo:7.0
        environment:
            MONGO_INITDB_ROOT_USERNAME: root
            MONGO_INITDB_ROOT_PASSWORD: root
        volumes:
            - ../../../.data/mongodb:/data/db
        ports:
            - 27017:27017
