@startuml ticket reservation sequence diagram

actor User
boundary Client
participant OrderService
queue MessageBroker
participant TicketService
participant MovieService
participant TheaterService
collections PaymentGateway

User -> Client ++: Request to reserve a ticket
Client -> OrderService ++: POST /orders
OrderService -> MovieService ++: Get movie information
return Movie information
OrderService -> TheaterService ++: Get theater information
return Theater information
OrderService -> OrderService : Create a new order
OrderService -> TicketService ++: Reserve ticket
return Ticket information\nand order ID
OrderService -> PaymentGateway ++: Initiate payment for the order
return Payment information
return Order, payment,\nand ticket information
return Order, payment,\nand ticket information

@enduml
