services:
    jaeger-collector:
        image: jaegertracing/jaeger-collector:latest
        command:
            - "--cassandra.keyspace=jaeger_v1_dc1"
            - "--cassandra.servers=cassandra"
            - "--collector.zipkin.host-port=9411"
            - "--sampling.initial-sampling-probability=.5"
            - "--sampling.target-samples-per-second=.01"
        environment:
            - SPAN_STORAGE_TYPE=cassandra
            - SAMPLING_CONFIG_TYPE=adaptive
        ports:
            - "14269:14269"
            - "14268:14268"
            - "14250:14250"
            - "9411:9411"
            - "4318:4317"
        restart: "on-failure:5"
        depends_on:
            - cassandra-schema
        networks:
            - monitoring-net

    jaeger-query:
        image: jaegertracing/jaeger-query:latest
        command:
            [
                "--cassandra.keyspace=jaeger_v1_dc1",
                "--cassandra.servers=cassandra",
            ]
        ports:
            - "16686:16686"
            - "16687"
        restart: "on-failure:5"
        depends_on:
            - cassandra-schema
        networks:
            - monitoring-net

    jaeger-agent:
        image: jaegertracing/jaeger-agent:latest
        command: ["--reporter.grpc.host-port=jaeger-collector:14250"]
        ports:
            - "5775:5775/udp"
            - "6831:6831/udp"
            - "6832:6832/udp"
            - "5778:5778"
        restart: "on-failure:5"
        depends_on:
            - jaeger-collector
        networks:
            - monitoring-net

    cassandra:
        image: cassandra:latest
        restart: "on-failure:5"
        ports:
            - 7001:7000
            - 9042:9042
        networks:
            - monitoring-net
        environment:
            - MAX_HEAP_SIZE=512M
            - HEAP_NEWSIZE=100M
        volumes:
            - ./.data/cassandra:/var/lib/cassandra:rw
        healthcheck:
            test: ["CMD-SHELL", "nodetool status"]
            interval: 2m
            start_period: 2m
            timeout: 10s
            retries: 3

    cassandra-schema:
        image: jaegertracing/jaeger-cassandra-schema:latest
        restart: "on-failure:5"
        depends_on:
            - cassandra
        networks:
            - monitoring-net
