services:
    jaeger-collector:
        image: jaegertracing/jaeger-collector:1.65.0
        command:
            - "--cassandra.servers=cassandra"
            - "--cassandra.keyspace=jaeger_v1_dc1"
            - "--collector.zipkin.host-port=9411"
            - "--sampling.initial-sampling-probability=.5"
            - "--sampling.target-samples-per-second=.01"
        environment:
            - SAMPLING_CONFIG_TYPE=adaptive
            - SPAN_STORAGE_TYPE=cassandra
        ports:
            - "14268:14268" # accept jaeger.thrift directly from clients
            - "14269:14269" # health check
            - "14250:14250" # accept model.proto
            - "9411:9411" # Zipkin compatible endpoint (optional)
            - "4317:4317" # accept OpenTelemetry Protocol (OTLP) over gRPC
            - "4318:4318" # accept OpenTelemetry Protocol (OTLP) over gHTTP
        restart: "on-failure:5"
        healthcheck:
            test: ["CMD", "curl", "-f", "http://localhost:14269"]
            interval: 30s
            timeout: 5s
            retries: 3
        depends_on:
            cassandra:
                condition: service_healthy
        networks:
            - monitoring-net

    jaeger-query:
        image: jaegertracing/jaeger-query:1.65.0
        command:
            - "--cassandra.servers=cassandra"
            - "--cassandra.keyspace=jaeger_v1_dc1"
        ports:
            - "16686:16686" # serve frontend
            - "16687:16687" # health check
        restart: "on-failure:5"
        healthcheck:
            test: ["CMD", "curl", "-f", "http://localhost:16687"]
            interval: 30s
            timeout: 5s
            retries: 3
        depends_on:
            - jaeger-collector
        networks:
            - monitoring-net

    cassandra:
        image: cassandra:5
        restart: "on-failure:5"
        expose:
            - 7000
            - 9042
        # ports:
        # For MacOS, AirPlay receiver may have started on Port 7000
        # - 7001:7000 # Port for inter-node communication
        # - 9042:9042 # Port where the CQL native transport listens for clients.
        networks:
            - monitoring-net
        environment:
            - MAX_HEAP_SIZE=512M
            - HEAP_NEWSIZE=100M
        volumes:
            - ./.data/cassandra:/var/lib/cassandra:rw
        healthcheck:
            test: ["CMD-SHELL", "nodetool status"]
            interval: 2m
            start_period: 2m
            timeout: 10s
            retries: 3

    # Schema migration: https://github.com/jaegertracing/jaeger/blob/main/plugin/storage/cassandra/schema/README.md
    # Code: https://github.com/jaegertracing/jaeger/blob/main/plugin/storage/cassandra/schema/docker.sh
    cassandra-schema:
        image: jaegertracing/jaeger-cassandra-schema:1.65.0
        restart: "on-failure:5"
        environment:
            - CQLSH_HOST=cassandra
        depends_on:
            cassandra:
                condition: service_healthy
        networks:
            - monitoring-net
