services:
    # Config reference: https://kafka.apache.org/documentation/#brokerconfigs
    kafka:
        image: apache/kafka:3.9.0
        ports:
            - "9092:9092"
        environment:
            KAFKA_NODE_ID: 1
            KAFKA_PROCESS_ROLES: broker,controller
            KAFKA_LISTENERS: INTERNAL://0.0.0.0:29092,EXTERNAL://0.0.0.0:9092,CONTROLLER://localhost:9093
            KAFKA_ADVERTISED_LISTENERS: INTERNAL://kafka:29092,EXTERNAL://localhost:9092
            KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
            KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,EXTERNAL:PLAINTEXT,INTERNAL:PLAINTEXT
            KAFKA_INTER_BROKER_LISTENER_NAME: "INTERNAL"
            KAFKA_CONTROLLER_QUORUM_VOTERS: 1@localhost:9093
            KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
            KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
            KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
            KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
            KAFKA_NUM_PARTITIONS: 3
            KAFKA_LOG_DIRS: /data
            KAFKA_RESTART_ATTEMPTS: "10"
            KAFKA_RESTART_DELAY: "5"
        volumes:
            - ./.data/kafka:/data
        networks:
            - core-net
        healthcheck:
            test:
                [
                    "CMD-SHELL",
                    "/opt/kafka/bin/kafka-topics.sh --list --bootstrap-server localhost:9092",
                ]
            interval: 30s
            timeout: 10s
            retries: 5

    kafka-exporter:
        image: danielqsj/kafka-exporter:latest
        environment:
            KAFKA_BROKERS: "kafka:9092"
        ports:
            - "9307:9308"
        depends_on:
            kafka:
                condition: service_healthy
        networks:
            - core-net
            - monitoring-net

    kafdrop:
        image: obsidiandynamics/kafdrop
        restart: "no"
        ports:
            - "9001:9000"
        environment:
            KAFKA_BROKERCONNECT: "kafka:29092"
        depends_on:
            kafka:
                condition: service_healthy
        networks:
            - core-net
