services:
    loki:
        image: grafana/loki:2.9.11
        volumes:
            - ./config/loki.yaml:/etc/loki/loki.yaml:ro
        ports:
            - 3100:3100
        command: -config.file=/etc/loki/loki.yaml
        depends_on:
            - minio
        networks:
            - monitoring-net
        healthcheck:
            test:
                [
                    "CMD-SHELL",
                    "wget --no-verbose --tries=1 --spider http://localhost:3100/ready || exit 1",
                ]
            interval: 10s
            timeout: 5s
            retries: 5

    minio:
        image: minio/minio:latest
        entrypoint:
            - sh
            - -euc
            - |
                mkdir -p /data/loki-data && \
                mkdir -p /data/loki-ruler &&
                minio server /data
        environment:
            - MINIO_ROOT_USER=loki
            - MINIO_ROOT_PASSWORD=supersecret
            - MINIO_PROMETHEUS_AUTH_TYPE=public
            - MINIO_UPDATE=off
        ports:
            - "9000:9000"
        volumes:
            - ./.data/minio:/data
        healthcheck:
            test: [ "CMD", "curl", "-f", "http://localhost:9000/minio/health/live" ]
            interval: 15s
            timeout: 20s
            retries: 5
        networks:
            - monitoring-net
