-- +migrate Up
CREATE TABLE seat (
    seat_id BINARY(16) PRIMARY KEY NOT NULL DEFAULT (UUID_TO_BIN(UUID())),
    trace_id VARCHAR(255) NOT NULL,
    room_id VARCHAR(255) NOT NULL,
    seat_row VARCHAR(255) NOT NULL,
    seat_column VARCHAR(255) NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    deleted_at TIMESTAMP
);

-- +migrate Down
DROP TABLE seat;
