root = ".."
tmp_dir = "./movie-service/.dist/air"

[build]
bin = "./.dist/air/server"
cmd = "go build -o ./.dist/air/server ./cmd/server/main.go"
delay = 1000
exclude_dir = ["movie-service/.coverage", "movie-service/.data", "movie-service/.dist", "movie-service/build", "movie-service/deploy"]
exclude_file = []
exclude_regex = []
exclude_unchanged = false
follow_symlink = false
full_bin = ""
include_dir = ["movie-service", "pkg", "user-service/pkg"]
include_ext = ["go", "tpl", "tmpl", "html"]
kill_delay = "0s"
log = "./build-errors.log"
send_interrupt = false
stop_on_error = true

[color]
app = ""
build = "yellow"
main = "magenta"
runner = "green"
watcher = "cyan"

[log]
time = false

[misc]
clean_on_exit = true
