// Code generated by mockery v2.42.1. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// Argon2Hasher is an autogenerated mock type for the Argon2Hasher type
type Argon2Hasher struct {
	mock.Mock
}

type Argon2Hasher_Expecter struct {
	mock *mock.Mock
}

func (_m *Argon2Hasher) EXPECT() *Argon2Hasher_Expecter {
	return &Argon2Hasher_Expecter{mock: &_m.Mock}
}

// Compare provides a mock function with given fields: hash, value
func (_m *Argon2Hasher) Compare(hash string, value string) (bool, error) {
	ret := _m.Called(hash, value)

	if len(ret) == 0 {
		panic("no return value specified for Compare")
	}

	var r0 bool
	var r1 error
	if rf, ok := ret.Get(0).(func(string, string) (bool, error)); ok {
		return rf(hash, value)
	}
	if rf, ok := ret.Get(0).(func(string, string) bool); ok {
		r0 = rf(hash, value)
	} else {
		r0 = ret.Get(0).(bool)
	}

	if rf, ok := ret.Get(1).(func(string, string) error); ok {
		r1 = rf(hash, value)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Argon2Hasher_Compare_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Compare'
type Argon2Hasher_Compare_Call struct {
	*mock.Call
}

// Compare is a helper method to define mock.On call
//   - hash string
//   - value string
func (_e *Argon2Hasher_Expecter) Compare(hash interface{}, value interface{}) *Argon2Hasher_Compare_Call {
	return &Argon2Hasher_Compare_Call{Call: _e.mock.On("Compare", hash, value)}
}

func (_c *Argon2Hasher_Compare_Call) Run(run func(hash string, value string)) *Argon2Hasher_Compare_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string), args[1].(string))
	})
	return _c
}

func (_c *Argon2Hasher_Compare_Call) Return(_a0 bool, _a1 error) *Argon2Hasher_Compare_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *Argon2Hasher_Compare_Call) RunAndReturn(run func(string, string) (bool, error)) *Argon2Hasher_Compare_Call {
	_c.Call.Return(run)
	return _c
}

// Hash provides a mock function with given fields: value
func (_m *Argon2Hasher) Hash(value string) (string, error) {
	ret := _m.Called(value)

	if len(ret) == 0 {
		panic("no return value specified for Hash")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(string) (string, error)); ok {
		return rf(value)
	}
	if rf, ok := ret.Get(0).(func(string) string); ok {
		r0 = rf(value)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(value)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Argon2Hasher_Hash_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Hash'
type Argon2Hasher_Hash_Call struct {
	*mock.Call
}

// Hash is a helper method to define mock.On call
//   - value string
func (_e *Argon2Hasher_Expecter) Hash(value interface{}) *Argon2Hasher_Hash_Call {
	return &Argon2Hasher_Hash_Call{Call: _e.mock.On("Hash", value)}
}

func (_c *Argon2Hasher_Hash_Call) Run(run func(value string)) *Argon2Hasher_Hash_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *Argon2Hasher_Hash_Call) Return(_a0 string, _a1 error) *Argon2Hasher_Hash_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *Argon2Hasher_Hash_Call) RunAndReturn(run func(string) (string, error)) *Argon2Hasher_Hash_Call {
	_c.Call.Return(run)
	return _c
}

// NewArgon2Hasher creates a new instance of Argon2Hasher. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewArgon2Hasher(t interface {
	mock.TestingT
	Cleanup(func())
}) *Argon2Hasher {
	mock := &Argon2Hasher{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
