// Code generated by mockery v2.42.1. DO NOT EDIT.

package mocks

import (
	gin "github.com/gin-gonic/gin"
	mock "github.com/stretchr/testify/mock"
)

// Validator is an autogenerated mock type for the Validator type
type Validator struct {
	mock.Mock
}

type Validator_Expecter struct {
	mock *mock.Mock
}

func (_m *Validator) EXPECT() *Validator_Expecter {
	return &Validator_Expecter{mock: &_m.Mock}
}

// ValidateBody provides a mock function with given fields: c, schema
func (_m *Validator) ValidateBody(c *gin.Context, schema interface{}) error {
	ret := _m.Called(c, schema)

	if len(ret) == 0 {
		panic("no return value specified for ValidateBody")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(*gin.Context, interface{}) error); ok {
		r0 = rf(c, schema)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Validator_ValidateBody_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ValidateBody'
type Validator_ValidateBody_Call struct {
	*mock.Call
}

// ValidateBody is a helper method to define mock.On call
//   - c *gin.Context
//   - schema interface{}
func (_e *Validator_Expecter) ValidateBody(c interface{}, schema interface{}) *Validator_ValidateBody_Call {
	return &Validator_ValidateBody_Call{Call: _e.mock.On("ValidateBody", c, schema)}
}

func (_c *Validator_ValidateBody_Call) Run(run func(c *gin.Context, schema interface{})) *Validator_ValidateBody_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*gin.Context), args[1].(interface{}))
	})
	return _c
}

func (_c *Validator_ValidateBody_Call) Return(_a0 error) *Validator_ValidateBody_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *Validator_ValidateBody_Call) RunAndReturn(run func(*gin.Context, interface{}) error) *Validator_ValidateBody_Call {
	_c.Call.Return(run)
	return _c
}

// ValidateQueryParams provides a mock function with given fields: c, schema
func (_m *Validator) ValidateQueryParams(c *gin.Context, schema interface{}) error {
	ret := _m.Called(c, schema)

	if len(ret) == 0 {
		panic("no return value specified for ValidateQueryParams")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(*gin.Context, interface{}) error); ok {
		r0 = rf(c, schema)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Validator_ValidateQueryParams_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ValidateQueryParams'
type Validator_ValidateQueryParams_Call struct {
	*mock.Call
}

// ValidateQueryParams is a helper method to define mock.On call
//   - c *gin.Context
//   - schema interface{}
func (_e *Validator_Expecter) ValidateQueryParams(c interface{}, schema interface{}) *Validator_ValidateQueryParams_Call {
	return &Validator_ValidateQueryParams_Call{Call: _e.mock.On("ValidateQueryParams", c, schema)}
}

func (_c *Validator_ValidateQueryParams_Call) Run(run func(c *gin.Context, schema interface{})) *Validator_ValidateQueryParams_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*gin.Context), args[1].(interface{}))
	})
	return _c
}

func (_c *Validator_ValidateQueryParams_Call) Return(_a0 error) *Validator_ValidateQueryParams_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *Validator_ValidateQueryParams_Call) RunAndReturn(run func(*gin.Context, interface{}) error) *Validator_ValidateQueryParams_Call {
	_c.Call.Return(run)
	return _c
}

// NewValidator creates a new instance of Validator. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewValidator(t interface {
	mock.TestingT
	Cleanup(func())
}) *Validator {
	mock := &Validator{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
