global:
    scrape_interval: 15s
    evaluation_interval: 15s

scrape_configs:
    - job_name: "prometheus"
      scrape_interval: 5s
      static_configs:
          - targets: ["localhost:9090"]

    - job_name: "kafka"
      static_configs:
          - targets: ["kafka-exporter:9307"]

    - job_name: "user-service-postgres"
      static_configs:
          - targets: ["user-service-postgres-exporter:9187"]

    - job_name: "user-service-redis"
      static_configs:
          - targets: ["user-service-redis-exporter:9121"]
