// Code generated by mockery v2.42.1. DO NOT EDIT.

package mocks

import (
	context "context"

	gin "github.com/gin-gonic/gin"
	error_pkg "github.com/harmonify/movie-reservation-system/pkg/error"

	http_pkg "github.com/harmonify/movie-reservation-system/pkg/http"

	mock "github.com/stretchr/testify/mock"
)

// HttpResponse is an autogenerated mock type for the HttpResponse type
type HttpResponse struct {
	mock.Mock
}

type HttpResponse_Expecter struct {
	mock *mock.Mock
}

func (_m *HttpResponse) EXPECT() *HttpResponse_Expecter {
	return &HttpResponse_Expecter{mock: &_m.Mock}
}

// Build provides a mock function with given fields: ctx, successHttpCode, data, err
func (_m *HttpResponse) Build(ctx context.Context, successHttpCode int, data interface{}, err *error_pkg.ErrorWithDetails) (int, *http_pkg.ResponseBodySchema) {
	ret := _m.Called(ctx, successHttpCode, data, err)

	if len(ret) == 0 {
		panic("no return value specified for Build")
	}

	var r0 int
	var r1 *http_pkg.ResponseBodySchema
	if rf, ok := ret.Get(0).(func(context.Context, int, interface{}, *error_pkg.ErrorWithDetails) (int, *http_pkg.ResponseBodySchema)); ok {
		return rf(ctx, successHttpCode, data, err)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int, interface{}, *error_pkg.ErrorWithDetails) int); ok {
		r0 = rf(ctx, successHttpCode, data, err)
	} else {
		r0 = ret.Get(0).(int)
	}

	if rf, ok := ret.Get(1).(func(context.Context, int, interface{}, *error_pkg.ErrorWithDetails) *http_pkg.ResponseBodySchema); ok {
		r1 = rf(ctx, successHttpCode, data, err)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*http_pkg.ResponseBodySchema)
		}
	}

	return r0, r1
}

// HttpResponse_Build_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Build'
type HttpResponse_Build_Call struct {
	*mock.Call
}

// Build is a helper method to define mock.On call
//   - ctx context.Context
//   - successHttpCode int
//   - data interface{}
//   - err *error_pkg.ErrorWithDetails
func (_e *HttpResponse_Expecter) Build(ctx interface{}, successHttpCode interface{}, data interface{}, err interface{}) *HttpResponse_Build_Call {
	return &HttpResponse_Build_Call{Call: _e.mock.On("Build", ctx, successHttpCode, data, err)}
}

func (_c *HttpResponse_Build_Call) Run(run func(ctx context.Context, successHttpCode int, data interface{}, err *error_pkg.ErrorWithDetails)) *HttpResponse_Build_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int), args[2].(interface{}), args[3].(*error_pkg.ErrorWithDetails))
	})
	return _c
}

func (_c *HttpResponse_Build_Call) Return(responseHttpCode int, responseBody *http_pkg.ResponseBodySchema) *HttpResponse_Build_Call {
	_c.Call.Return(responseHttpCode, responseBody)
	return _c
}

func (_c *HttpResponse_Build_Call) RunAndReturn(run func(context.Context, int, interface{}, *error_pkg.ErrorWithDetails) (int, *http_pkg.ResponseBodySchema)) *HttpResponse_Build_Call {
	_c.Call.Return(run)
	return _c
}

// Send provides a mock function with given fields: c, data, err
func (_m *HttpResponse) Send(c *gin.Context, data interface{}, err error) {
	_m.Called(c, data, err)
}

// HttpResponse_Send_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Send'
type HttpResponse_Send_Call struct {
	*mock.Call
}

// Send is a helper method to define mock.On call
//   - c *gin.Context
//   - data interface{}
//   - err error
func (_e *HttpResponse_Expecter) Send(c interface{}, data interface{}, err interface{}) *HttpResponse_Send_Call {
	return &HttpResponse_Send_Call{Call: _e.mock.On("Send", c, data, err)}
}

func (_c *HttpResponse_Send_Call) Run(run func(c *gin.Context, data interface{}, err error)) *HttpResponse_Send_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*gin.Context), args[1].(interface{}), args[2].(error))
	})
	return _c
}

func (_c *HttpResponse_Send_Call) Return() *HttpResponse_Send_Call {
	_c.Call.Return()
	return _c
}

func (_c *HttpResponse_Send_Call) RunAndReturn(run func(*gin.Context, interface{}, error)) *HttpResponse_Send_Call {
	_c.Call.Return(run)
	return _c
}

// SendWithResponseCode provides a mock function with given fields: c, successHttpCode, data, err
func (_m *HttpResponse) SendWithResponseCode(c *gin.Context, successHttpCode int, data interface{}, err error) {
	_m.Called(c, successHttpCode, data, err)
}

// HttpResponse_SendWithResponseCode_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SendWithResponseCode'
type HttpResponse_SendWithResponseCode_Call struct {
	*mock.Call
}

// SendWithResponseCode is a helper method to define mock.On call
//   - c *gin.Context
//   - successHttpCode int
//   - data interface{}
//   - err error
func (_e *HttpResponse_Expecter) SendWithResponseCode(c interface{}, successHttpCode interface{}, data interface{}, err interface{}) *HttpResponse_SendWithResponseCode_Call {
	return &HttpResponse_SendWithResponseCode_Call{Call: _e.mock.On("SendWithResponseCode", c, successHttpCode, data, err)}
}

func (_c *HttpResponse_SendWithResponseCode_Call) Run(run func(c *gin.Context, successHttpCode int, data interface{}, err error)) *HttpResponse_SendWithResponseCode_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*gin.Context), args[1].(int), args[2].(interface{}), args[3].(error))
	})
	return _c
}

func (_c *HttpResponse_SendWithResponseCode_Call) Return() *HttpResponse_SendWithResponseCode_Call {
	_c.Call.Return()
	return _c
}

func (_c *HttpResponse_SendWithResponseCode_Call) RunAndReturn(run func(*gin.Context, int, interface{}, error)) *HttpResponse_SendWithResponseCode_Call {
	_c.Call.Return(run)
	return _c
}

// NewHttpResponse creates a new instance of HttpResponse. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewHttpResponse(t interface {
	mock.TestingT
	Cleanup(func())
}) *HttpResponse {
	mock := &HttpResponse{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
