// Code generated by mockery v2.42.1. DO NOT EDIT.

package mocks

import (
	gin "github.com/gin-gonic/gin"
	mock "github.com/stretchr/testify/mock"
)

// HttpValidator is an autogenerated mock type for the HttpValidator type
type HttpValidator struct {
	mock.Mock
}

type HttpValidator_Expecter struct {
	mock *mock.Mock
}

func (_m *HttpValidator) EXPECT() *HttpValidator_Expecter {
	return &HttpValidator_Expecter{mock: &_m.Mock}
}

// Validate provides a mock function with given fields: c, schema
func (_m *HttpValidator) Validate(c *gin.Context, schema interface{}) error {
	ret := _m.Called(c, schema)

	if len(ret) == 0 {
		panic("no return value specified for Validate")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(*gin.Context, interface{}) error); ok {
		r0 = rf(c, schema)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// HttpValidator_Validate_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Validate'
type HttpValidator_Validate_Call struct {
	*mock.Call
}

// Validate is a helper method to define mock.On call
//   - c *gin.Context
//   - schema interface{}
func (_e *HttpValidator_Expecter) Validate(c interface{}, schema interface{}) *HttpValidator_Validate_Call {
	return &HttpValidator_Validate_Call{Call: _e.mock.On("Validate", c, schema)}
}

func (_c *HttpValidator_Validate_Call) Run(run func(c *gin.Context, schema interface{})) *HttpValidator_Validate_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*gin.Context), args[1].(interface{}))
	})
	return _c
}

func (_c *HttpValidator_Validate_Call) Return(_a0 error) *HttpValidator_Validate_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *HttpValidator_Validate_Call) RunAndReturn(run func(*gin.Context, interface{}) error) *HttpValidator_Validate_Call {
	_c.Call.Return(run)
	return _c
}

// ValidateQueryParams provides a mock function with given fields: c, schema
func (_m *HttpValidator) ValidateQueryParams(c *gin.Context, schema interface{}) error {
	ret := _m.Called(c, schema)

	if len(ret) == 0 {
		panic("no return value specified for ValidateQueryParams")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(*gin.Context, interface{}) error); ok {
		r0 = rf(c, schema)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// HttpValidator_ValidateQueryParams_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ValidateQueryParams'
type HttpValidator_ValidateQueryParams_Call struct {
	*mock.Call
}

// ValidateQueryParams is a helper method to define mock.On call
//   - c *gin.Context
//   - schema interface{}
func (_e *HttpValidator_Expecter) ValidateQueryParams(c interface{}, schema interface{}) *HttpValidator_ValidateQueryParams_Call {
	return &HttpValidator_ValidateQueryParams_Call{Call: _e.mock.On("ValidateQueryParams", c, schema)}
}

func (_c *HttpValidator_ValidateQueryParams_Call) Run(run func(c *gin.Context, schema interface{})) *HttpValidator_ValidateQueryParams_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*gin.Context), args[1].(interface{}))
	})
	return _c
}

func (_c *HttpValidator_ValidateQueryParams_Call) Return(_a0 error) *HttpValidator_ValidateQueryParams_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *HttpValidator_ValidateQueryParams_Call) RunAndReturn(run func(*gin.Context, interface{}) error) *HttpValidator_ValidateQueryParams_Call {
	_c.Call.Return(run)
	return _c
}

// NewHttpValidator creates a new instance of HttpValidator. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewHttpValidator(t interface {
	mock.TestingT
	Cleanup(func())
}) *HttpValidator {
	mock := &HttpValidator{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
