// Code generated by mockery v2.42.1. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// HttpErrorHandler is an autogenerated mock type for the HttpErrorHandler type
type HttpErrorHandler struct {
	mock.Mock
}

type HttpErrorHandler_Expecter struct {
	mock *mock.Mock
}

func (_m *HttpErrorHandler) EXPECT() *HttpErrorHandler_Expecter {
	return &HttpErrorHandler_Expecter{mock: &_m.Mock}
}

// Error provides a mock function with given fields:
func (_m *HttpErrorHandler) Error() string {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Error")
	}

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// HttpErrorHandler_Error_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Error'
type HttpErrorHandler_Error_Call struct {
	*mock.Call
}

// Error is a helper method to define mock.On call
func (_e *HttpErrorHandler_Expecter) Error() *HttpErrorHandler_Error_Call {
	return &HttpErrorHandler_Error_Call{Call: _e.mock.On("Error")}
}

func (_c *HttpErrorHandler_Error_Call) Run(run func()) *HttpErrorHandler_Error_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *HttpErrorHandler_Error_Call) Return(_a0 string) *HttpErrorHandler_Error_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *HttpErrorHandler_Error_Call) RunAndReturn(run func() string) *HttpErrorHandler_Error_Call {
	_c.Call.Return(run)
	return _c
}

// NewHttpErrorHandler creates a new instance of HttpErrorHandler. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewHttpErrorHandler(t interface {
	mock.TestingT
	Cleanup(func())
}) *HttpErrorHandler {
	mock := &HttpErrorHandler{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
