// Code generated by mockery v2.42.1. DO NOT EDIT.

package mocks

import (
	gin "github.com/gin-gonic/gin"

	jwt_util "github.com/harmonify/movie-reservation-system/pkg/util/jwt"

	mock "github.com/stretchr/testify/mock"
)

// JwtRbacHttpMiddleware is an autogenerated mock type for the JwtRbacHttpMiddleware type
type JwtRbacHttpMiddleware struct {
	mock.Mock
}

type JwtRbacHttpMiddleware_Expecter struct {
	mock *mock.Mock
}

func (_m *JwtRbacHttpMiddleware) EXPECT() *JwtRbacHttpMiddleware_Expecter {
	return &JwtRbacHttpMiddleware_Expecter{mock: &_m.Mock}
}

// CheckPermissions provides a mock function with given fields: _a0
func (_m *JwtRbacHttpMiddleware) CheckPermissions(_a0 func(*jwt_util.JWTBodyPayload) bool) gin.HandlerFunc {
	ret := _m.Called(_a0)

	if len(ret) == 0 {
		panic("no return value specified for CheckPermissions")
	}

	var r0 gin.HandlerFunc
	if rf, ok := ret.Get(0).(func(func(*jwt_util.JWTBodyPayload) bool) gin.HandlerFunc); ok {
		r0 = rf(_a0)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(gin.HandlerFunc)
		}
	}

	return r0
}

// JwtRbacHttpMiddleware_CheckPermissions_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CheckPermissions'
type JwtRbacHttpMiddleware_CheckPermissions_Call struct {
	*mock.Call
}

// CheckPermissions is a helper method to define mock.On call
//   - _a0 func(*jwt_util.JWTBodyPayload) bool
func (_e *JwtRbacHttpMiddleware_Expecter) CheckPermissions(_a0 interface{}) *JwtRbacHttpMiddleware_CheckPermissions_Call {
	return &JwtRbacHttpMiddleware_CheckPermissions_Call{Call: _e.mock.On("CheckPermissions", _a0)}
}

func (_c *JwtRbacHttpMiddleware_CheckPermissions_Call) Run(run func(_a0 func(*jwt_util.JWTBodyPayload) bool)) *JwtRbacHttpMiddleware_CheckPermissions_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(func(*jwt_util.JWTBodyPayload) bool))
	})
	return _c
}

func (_c *JwtRbacHttpMiddleware_CheckPermissions_Call) Return(_a0 gin.HandlerFunc) *JwtRbacHttpMiddleware_CheckPermissions_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *JwtRbacHttpMiddleware_CheckPermissions_Call) RunAndReturn(run func(func(*jwt_util.JWTBodyPayload) bool) gin.HandlerFunc) *JwtRbacHttpMiddleware_CheckPermissions_Call {
	_c.Call.Return(run)
	return _c
}

// NewJwtRbacHttpMiddleware creates a new instance of JwtRbacHttpMiddleware. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewJwtRbacHttpMiddleware(t interface {
	mock.TestingT
	Cleanup(func())
}) *JwtRbacHttpMiddleware {
	mock := &JwtRbacHttpMiddleware{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
