// Code generated by mockery v2.42.1. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// lokiSink is an autogenerated mock type for the lokiSink type
type lokiSink struct {
	mock.Mock
}

type lokiSink_Expecter struct {
	mock *mock.Mock
}

func (_m *lokiSink) EXPECT() *lokiSink_Expecter {
	return &lokiSink_Expecter{mock: &_m.Mock}
}

// Close provides a mock function with given fields:
func (_m *lokiSink) Close() error {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Close")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func() error); ok {
		r0 = rf()
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// lokiSink_Close_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Close'
type lokiSink_Close_Call struct {
	*mock.Call
}

// Close is a helper method to define mock.On call
func (_e *lokiSink_Expecter) Close() *lokiSink_Close_Call {
	return &lokiSink_Close_Call{Call: _e.mock.On("Close")}
}

func (_c *lokiSink_Close_Call) Run(run func()) *lokiSink_Close_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *lokiSink_Close_Call) Return(_a0 error) *lokiSink_Close_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *lokiSink_Close_Call) RunAndReturn(run func() error) *lokiSink_Close_Call {
	_c.Call.Return(run)
	return _c
}

// Sync provides a mock function with given fields:
func (_m *lokiSink) Sync() error {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Sync")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func() error); ok {
		r0 = rf()
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// lokiSink_Sync_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Sync'
type lokiSink_Sync_Call struct {
	*mock.Call
}

// Sync is a helper method to define mock.On call
func (_e *lokiSink_Expecter) Sync() *lokiSink_Sync_Call {
	return &lokiSink_Sync_Call{Call: _e.mock.On("Sync")}
}

func (_c *lokiSink_Sync_Call) Run(run func()) *lokiSink_Sync_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *lokiSink_Sync_Call) Return(_a0 error) *lokiSink_Sync_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *lokiSink_Sync_Call) RunAndReturn(run func() error) *lokiSink_Sync_Call {
	_c.Call.Return(run)
	return _c
}

// Write provides a mock function with given fields: p
func (_m *lokiSink) Write(p []byte) (int, error) {
	ret := _m.Called(p)

	if len(ret) == 0 {
		panic("no return value specified for Write")
	}

	var r0 int
	var r1 error
	if rf, ok := ret.Get(0).(func([]byte) (int, error)); ok {
		return rf(p)
	}
	if rf, ok := ret.Get(0).(func([]byte) int); ok {
		r0 = rf(p)
	} else {
		r0 = ret.Get(0).(int)
	}

	if rf, ok := ret.Get(1).(func([]byte) error); ok {
		r1 = rf(p)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// lokiSink_Write_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Write'
type lokiSink_Write_Call struct {
	*mock.Call
}

// Write is a helper method to define mock.On call
//   - p []byte
func (_e *lokiSink_Expecter) Write(p interface{}) *lokiSink_Write_Call {
	return &lokiSink_Write_Call{Call: _e.mock.On("Write", p)}
}

func (_c *lokiSink_Write_Call) Run(run func(p []byte)) *lokiSink_Write_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].([]byte))
	})
	return _c
}

func (_c *lokiSink_Write_Call) Return(_a0 int, _a1 error) *lokiSink_Write_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *lokiSink_Write_Call) RunAndReturn(run func([]byte) (int, error)) *lokiSink_Write_Call {
	_c.Call.Return(run)
	return _c
}

// newLokiSink creates a new instance of lokiSink. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func newLokiSink(t interface {
	mock.TestingT
	Cleanup(func())
}) *lokiSink {
	mock := &lokiSink{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
