// Code generated by mockery v2.42.1. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
)

// StructUtil is an autogenerated mock type for the StructUtil type
type StructUtil struct {
	mock.Mock
}

type StructUtil_Expecter struct {
	mock *mock.Mock
}

func (_m *StructUtil) EXPECT() *StructUtil_Expecter {
	return &StructUtil_Expecter{mock: &_m.Mock}
}

// ConvertProtoToMap provides a mock function with given fields: ctx, msg
func (_m *StructUtil) ConvertProtoToMap(ctx context.Context, msg protoreflect.ProtoMessage) (map[string]interface{}, error) {
	ret := _m.Called(ctx, msg)

	if len(ret) == 0 {
		panic("no return value specified for ConvertProtoToMap")
	}

	var r0 map[string]interface{}
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, protoreflect.ProtoMessage) (map[string]interface{}, error)); ok {
		return rf(ctx, msg)
	}
	if rf, ok := ret.Get(0).(func(context.Context, protoreflect.ProtoMessage) map[string]interface{}); ok {
		r0 = rf(ctx, msg)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(map[string]interface{})
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, protoreflect.ProtoMessage) error); ok {
		r1 = rf(ctx, msg)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// StructUtil_ConvertProtoToMap_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ConvertProtoToMap'
type StructUtil_ConvertProtoToMap_Call struct {
	*mock.Call
}

// ConvertProtoToMap is a helper method to define mock.On call
//   - ctx context.Context
//   - msg protoreflect.ProtoMessage
func (_e *StructUtil_Expecter) ConvertProtoToMap(ctx interface{}, msg interface{}) *StructUtil_ConvertProtoToMap_Call {
	return &StructUtil_ConvertProtoToMap_Call{Call: _e.mock.On("ConvertProtoToMap", ctx, msg)}
}

func (_c *StructUtil_ConvertProtoToMap_Call) Run(run func(ctx context.Context, msg protoreflect.ProtoMessage)) *StructUtil_ConvertProtoToMap_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(protoreflect.ProtoMessage))
	})
	return _c
}

func (_c *StructUtil_ConvertProtoToMap_Call) Return(_a0 map[string]interface{}, _a1 error) *StructUtil_ConvertProtoToMap_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *StructUtil_ConvertProtoToMap_Call) RunAndReturn(run func(context.Context, protoreflect.ProtoMessage) (map[string]interface{}, error)) *StructUtil_ConvertProtoToMap_Call {
	_c.Call.Return(run)
	return _c
}

// ConvertSqlStructToMap provides a mock function with given fields: ctx, input
func (_m *StructUtil) ConvertSqlStructToMap(ctx context.Context, input interface{}) (map[string]interface{}, error) {
	ret := _m.Called(ctx, input)

	if len(ret) == 0 {
		panic("no return value specified for ConvertSqlStructToMap")
	}

	var r0 map[string]interface{}
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, interface{}) (map[string]interface{}, error)); ok {
		return rf(ctx, input)
	}
	if rf, ok := ret.Get(0).(func(context.Context, interface{}) map[string]interface{}); ok {
		r0 = rf(ctx, input)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(map[string]interface{})
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, interface{}) error); ok {
		r1 = rf(ctx, input)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// StructUtil_ConvertSqlStructToMap_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ConvertSqlStructToMap'
type StructUtil_ConvertSqlStructToMap_Call struct {
	*mock.Call
}

// ConvertSqlStructToMap is a helper method to define mock.On call
//   - ctx context.Context
//   - input interface{}
func (_e *StructUtil_Expecter) ConvertSqlStructToMap(ctx interface{}, input interface{}) *StructUtil_ConvertSqlStructToMap_Call {
	return &StructUtil_ConvertSqlStructToMap_Call{Call: _e.mock.On("ConvertSqlStructToMap", ctx, input)}
}

func (_c *StructUtil_ConvertSqlStructToMap_Call) Run(run func(ctx context.Context, input interface{})) *StructUtil_ConvertSqlStructToMap_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(interface{}))
	})
	return _c
}

func (_c *StructUtil_ConvertSqlStructToMap_Call) Return(_a0 map[string]interface{}, _a1 error) *StructUtil_ConvertSqlStructToMap_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *StructUtil_ConvertSqlStructToMap_Call) RunAndReturn(run func(context.Context, interface{}) (map[string]interface{}, error)) *StructUtil_ConvertSqlStructToMap_Call {
	_c.Call.Return(run)
	return _c
}

// SetNonPrimitiveDefaultValue provides a mock function with given fields: ctx, data
func (_m *StructUtil) SetNonPrimitiveDefaultValue(ctx context.Context, data interface{}) interface{} {
	ret := _m.Called(ctx, data)

	if len(ret) == 0 {
		panic("no return value specified for SetNonPrimitiveDefaultValue")
	}

	var r0 interface{}
	if rf, ok := ret.Get(0).(func(context.Context, interface{}) interface{}); ok {
		r0 = rf(ctx, data)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(interface{})
		}
	}

	return r0
}

// StructUtil_SetNonPrimitiveDefaultValue_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetNonPrimitiveDefaultValue'
type StructUtil_SetNonPrimitiveDefaultValue_Call struct {
	*mock.Call
}

// SetNonPrimitiveDefaultValue is a helper method to define mock.On call
//   - ctx context.Context
//   - data interface{}
func (_e *StructUtil_Expecter) SetNonPrimitiveDefaultValue(ctx interface{}, data interface{}) *StructUtil_SetNonPrimitiveDefaultValue_Call {
	return &StructUtil_SetNonPrimitiveDefaultValue_Call{Call: _e.mock.On("SetNonPrimitiveDefaultValue", ctx, data)}
}

func (_c *StructUtil_SetNonPrimitiveDefaultValue_Call) Run(run func(ctx context.Context, data interface{})) *StructUtil_SetNonPrimitiveDefaultValue_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(interface{}))
	})
	return _c
}

func (_c *StructUtil_SetNonPrimitiveDefaultValue_Call) Return(result interface{}) *StructUtil_SetNonPrimitiveDefaultValue_Call {
	_c.Call.Return(result)
	return _c
}

func (_c *StructUtil_SetNonPrimitiveDefaultValue_Call) RunAndReturn(run func(context.Context, interface{}) interface{}) *StructUtil_SetNonPrimitiveDefaultValue_Call {
	_c.Call.Return(run)
	return _c
}

// NewStructUtil creates a new instance of StructUtil. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewStructUtil(t interface {
	mock.TestingT
	Cleanup(func())
}) *StructUtil {
	mock := &StructUtil{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
