// Code generated by mockery v2.42.1. DO NOT EDIT.

package mocks

import (
	auth_rest "github.com/harmonify/movie-reservation-system/user-service/internal/driver/http/auth"
	mock "github.com/stretchr/testify/mock"
)

// PostVerifyEmailTestConfig is an autogenerated mock type for the PostVerifyEmailTestConfig type
type PostVerifyEmailTestConfig struct {
	mock.Mock
}

type PostVerifyEmailTestConfig_Expecter struct {
	mock *mock.Mock
}

func (_m *PostVerifyEmailTestConfig) EXPECT() *PostVerifyEmailTestConfig_Expecter {
	return &PostVerifyEmailTestConfig_Expecter{mock: &_m.Mock}
}

// Execute provides a mock function with given fields:
func (_m *PostVerifyEmailTestConfig) Execute() auth_rest.PostVerifyEmailReq {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Execute")
	}

	var r0 auth_rest.PostVerifyEmailReq
	if rf, ok := ret.Get(0).(func() auth_rest.PostVerifyEmailReq); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(auth_rest.PostVerifyEmailReq)
	}

	return r0
}

// PostVerifyEmailTestConfig_Execute_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Execute'
type PostVerifyEmailTestConfig_Execute_Call struct {
	*mock.Call
}

// Execute is a helper method to define mock.On call
func (_e *PostVerifyEmailTestConfig_Expecter) Execute() *PostVerifyEmailTestConfig_Execute_Call {
	return &PostVerifyEmailTestConfig_Execute_Call{Call: _e.mock.On("Execute")}
}

func (_c *PostVerifyEmailTestConfig_Execute_Call) Run(run func()) *PostVerifyEmailTestConfig_Execute_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *PostVerifyEmailTestConfig_Execute_Call) Return(_a0 auth_rest.PostVerifyEmailReq) *PostVerifyEmailTestConfig_Execute_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *PostVerifyEmailTestConfig_Execute_Call) RunAndReturn(run func() auth_rest.PostVerifyEmailReq) *PostVerifyEmailTestConfig_Execute_Call {
	_c.Call.Return(run)
	return _c
}

// NewPostVerifyEmailTestConfig creates a new instance of PostVerifyEmailTestConfig. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewPostVerifyEmailTestConfig(t interface {
	mock.TestingT
	Cleanup(func())
}) *PostVerifyEmailTestConfig {
	mock := &PostVerifyEmailTestConfig{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
