services:
    order-service-postgres:
        image: debezium/postgres:16-alpine
        restart: "on-failure:5"
        environment:
            POSTGRES_USER: root
            POSTGRES_PASSWORD: root
            POSTGRES_DB: mrs-order-service
        ports:
            - 5433:5432
        volumes:
            - ./config/postgresql:/docker-entrypoint-initdb.d
            - ../../../.data/postgres:/data
        networks:
            - order-service-net

    order-service-redis:
        image: redis:7
        command: ["redis-server", "--requirepass", "secret"]
        ports:
            - "6383:6379"
        networks:
            - order-service-net
