apiVersion: 1
datasources:
  - name: loki
    type: loki
    uid: loki
    url: http://loki:3100
    access: proxy
    basicAuth: false
    jsonData:
      httpHeaderName1: "X-Scope-OrgID"
    secureJsonData:
      httpHeaderValue1: "docker"
    editable: true
    version: 1
    isDefault: true

  - name: Jaeger
    type: jaeger
    uid: jaeger
    url: http://jaeger-query:16686
    access: proxy
    basicAuth: false
    editable: true
    version: 1