services:
    user-service-postgres:
        image: debezium/postgres:17-alpine
        restart: "on-failure:5"
        environment:
            POSTGRES_USER: root
            POSTGRES_PASSWORD: root
            POSTGRES_DB: mvs-user-service
        ports:
            - 5432:5432
        volumes:
            - ./config/postgresql:/docker-entrypoint-initdb.d
            - ../../../.data/postgres:/data
        networks:
            - user-service-net

    user-service-connect:
        image: quay.io/debezium/connect:3.0
        environment:
            BOOTSTRAP_SERVERS: kafka:29092
            GROUP_ID: "1"
            CONFIG_STORAGE_TOPIC: user_connect_configs
            OFFSET_STORAGE_TOPIC: user_connect_offsets
            STATUS_STORAGE_TOPIC: user_connect_statuses
            # https://kafka.apache.org/documentation/#connect_running
            CONNECT_REST_ADVERTISED_LISTENER: connect
            CONNECT_REST_HOST: 0.0.0.0
            CONNECT_REST_PORT: 8083
        ports:
            - "8083:8083"
        depends_on:
            - kafka
            - user-service-postgres
        networks:
            - user-service-net
            - core-net

    user-service-postgres-exporter:
        image: prometheuscommunity/postgres-exporter:latest
        environment:
            DATA_SOURCE_URI: "postgres:5432/mvs-user-service?sslmode=disable"
            DATA_SOURCE_USER: "root"
            DATA_SOURCE_PASS: "root"
        ports:
            - "9187:9187"
        depends_on:
            - user-service-postgres
        networks:
            - user-service-net
            - monitoring-net

    user-service-redis:
        image: redis:latest
        command: ["redis-server", "--requirepass", "secret"]
        ports:
            - "6379:6379"
        networks:
            - user-service-net

    user-service-redis-exporter:
        image: oliver006/redis_exporter:latest
        environment:
            REDIS_PASSWORD: "secret"
        ports:
            - "9121:9121"
        depends_on:
            - user-service-redis
        networks:
            - user-service-net
            - monitoring-net

networks:
    user-service-net:
