services:
    movie-search-service-elasticsearch:
        image: elasticsearch:8.17.0
        expose:
            - "9200"
        ports:
            - "9200:9200"
        environment:
            - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
            - "ELASTIC_PASSWORD=elastic"
            - "action.destructive_requires_name=false"
            - "discovery.type=single-node"
            - "node.name=elasticsearch"
            - "xpack.security.enabled=true"
            - "xpack.security.authc.api_key.enabled=true"
            - "xpack.security.authc.token.enabled=true"
        ulimits:
            memlock:
                soft: -1
                hard: -1
        volumes:
            - ../../../.data/elasticsearch:/usr/share/elasticsearch/data
        networks:
            - movie-search-service-net
        healthcheck:
            # https://www.elastic.co/guide/en/elasticsearch/reference/8.17/cluster-health.html
            test:
                [
                    "CMD",
                    "curl",
                    "-X",
                    "GET",
                    "-u",
                    "elastic:elastic",
                    "localhost:9200/_cluster/health?wait_for_status=yellow&timeout=50s",
                ]
            interval: 30s
            timeout: 10s
            retries: 5

    movie-search-service-update-kibana-user-password:
        image: curlimages/curl:8.12.1
        command:
            [
                "sh",
                "-c",
                'curl -u elastic:elastic -X POST http://movie-search-service-elasticsearch:9200/_security/user/kibana_system/_password?pretty -H ''Content-Type: application/json'' -d ''{"password":"elastic"}''',
            ]
        networks:
            - movie-search-service-net
        depends_on:
            movie-search-service-elasticsearch:
                condition: service_healthy

    # Log in to the Web UI at http://localhost:5601 with the default credentials:
    # - Username: elastic
    # - Password: elastic
    # Dev Tools: http://localhost:5601/app/dev_tools#/console/shell
    movie-search-service-kibana:
        image: kibana:8.17.0
        ports:
            - "5601:5601"
        environment:
            - ELASTICSEARCH_URL=http://movie-search-service-elasticsearch:9200
            - ELASTICSEARCH_HOSTS=http://movie-search-service-elasticsearch:9200
            - ELASTICSEARCH_USERNAME=kibana_system
            - ELASTICSEARCH_PASSWORD=elastic
            - XPACK_MONITORING_ENABLED=true
            - XPACK_MONITORING_COLLECTION_ENABLED=true
            - XPACK_SECURITY_ENABLED=true
        networks:
            - movie-search-service-net
        depends_on:
            movie-search-service-elasticsearch:
                condition: service_healthy
            movie-search-service-update-kibana-user-password:
                condition: service_completed_successfully

    movie-search-service-redis:
        image: redis:7
        command: ["redis-server", "--requirepass", "secret"]
        ports:
            - "6381:6379"
        networks:
            - movie-search-service-net
