services:
    elasticsearch:
        image: elasticsearch:8.17.0
        ports:
            - "9200:9200"
        environment:
            - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
            - bootstrap.memory_lock=true
            - discovery.type=single-node
            - node.name=elasticsearch
        volumes:
            - ../../../.data/elasticsearch:/usr/share/elasticsearch/data
        networks:
            - movie-search-service-net

networks:
    movie-search-service-net:
